main_app/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('patients/', views.patients_index, name='index'),  
    path('patients/<int:patient_id>/', views.patients_details, name='details'),  
    path('patients/create/', views.patient_create.as_view(), name='patient_create'),
    path('patients/<int:pk>/update/', views.patient_update.as_view(), name='patient_update'),
    path('patients/<int:pk>/delete/', views.patients_delete.as_view(), name='patient_delete'),
    path('patients/<int:patient_id>/bloodSample_add/', views.bloodSample_add, name='bloodSample_add'),
    path('patients/<int:patient_id>/medication/<int:medication_id>/', views.patient_medication, name='patient_medication'),
    path('medication/', views.medicationList.as_view(), name='medication_index'),
    path('medication/create/', views.medication_create.as_view(), name='medication_create'),
    
    path('medication/<int:medication_id>/', views.patient_medication, name='medication_detail'),
    path('patients/<int:patient_id>/add_photo/', views.add_photo, name='add_photo'), 
    path('accounts/', include ('django.contrib.auth.urls')),
    path('accounts/signup', views.signup, name='signup'), 

]

samplingcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),

]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Medications(models.Model):
    name = models.CharField(max_length=200)
    startDate= models.DateField()
    endDate = models.DateField()
    amount = models.IntegerField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('medications_detail', kwargs={'pk': self.id})
        

class Patient (models.Model):
    name = models.CharField(max_length = 100)
    age = models.IntegerField()
    sex = models.CharField(max_length = 10)
    HealthCareNumber = models.IntegerField()
    familyDoctor = models.CharField(max_length = 100, default="Dr. Martin")
    medications = models.ManyToManyField(Medications)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('details', kwargs={'patient_id': self.id})

class BloodSamples (models.Model):   
    collectionDate = models.DateField()
    orderingPhysician = models.CharField(max_length = 100)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE,default=1)


class BloodSampleResult (models.Model):
    WBC = models.DecimalField(max_digits=5, decimal_places=1)
    RBC = models.DecimalField(max_digits=5, decimal_places=1)
    HCT = models.DecimalField(max_digits=5, decimal_places=1)
    MCV = models.DecimalField(max_digits=5, decimal_places=1)
    MCH = models.DecimalField(max_digits=5, decimal_places=1)
    Lymphocyte = models.DecimalField(max_digits=5, decimal_places=1)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, default=1 )

class Photo(models.Model):
    url = models.CharField(max_length=200)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for patient_id: {self.patient_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Patient, BloodSamples

class PatientForm(ModelForm):
  class Meta:
    model = Patient
    fields = ['name', 'age', 'sex', 'familyDoctor','HealthCareNumber']

class PatientBloodSampleForm(ModelForm):
    class Meta:
        model = BloodSamples
        fields = ['collectionDate', 'orderingPhysician']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Patient, BloodSamples, Medications, BloodSampleResult , Photo
from .forms import PatientBloodSampleForm

import boto3
import uuid

S3_BASE_URL = 'https://s3.us-east-1.amazonaws.com/'
BUCKET = 'gacatcollectordjango'

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid credentials - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)


def add_photo(request, patient_id):
  photo_file = request.FILES.get('photo-file', None)
  if photo_file:
    s3 = boto3.client('s3')
    key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
    try:
      s3.upload_fileobj(photo_file, BUCKET, key)
      url = f"{S3_BASE_URL}{BUCKET}/{key}"
      photo = Photo(url=url, patient_id=patient_id)
      print (photo)
      photo.save()
    except Exception as e:
      print (e)
      print("An error occurred uploading file to s3")
    
  return redirect('details', patient_id=patient_id)


class patient_create(CreateView):
  model = Patient
  fields = ['name', 'age', 'sex', 'age', 'HealthCareNumber', 'familyDoctor']


class patient_update(UpdateView):
    model = Patient
    fields = '__all__'
    patients = Patient.objects.all()
    success_url = "/patients"


class patients_delete(DeleteView):
    model = Patient
    success_url = '/patients/'


def home(request):
  return render(request, 'index.html')


def about(request):
    return render(request, 'about.html')


def patients_index(request):   
    patients = Patient.objects.all()
    return render(request, 'patients/index.html', {'patients':patients})
    

def patients_details(request, patient_id):
    patient = Patient.objects.get(id=patient_id)
    medication_patient_doesnt_have = Medications.objects.exclude(id__in = patient.medications.all().values_list('id'))
    patientBloodSample_form = PatientBloodSampleForm()
    return render(request, 'patients/detail.html', {
        'patient': patient, 'patientBloodSample_form': patientBloodSample_form, 'medications': medication_patient_doesnt_have
    })


def bloodSample_add (request, patient_id):
    form = PatientBloodSampleForm(request.POST)
    if form.is_valid():
        new_BloodSamples = form.save(commit=False)
        new_BloodSamples.patient_id = patient_id
        new_BloodSamples.save()
    return redirect('details', patient_id=patient_id)


def patient_medication(request,  medication_id):
  medications = Medications.objects.get(id=medication_id)
  return render(request, 'main_app/medications_detail.html', {'medication':medications})


class medicationList(ListView):
  model = Medications
  # template_name = "medication_List.html"
  # context_object_name="medication"


class medication_create(CreateView):
  model = Medications
  fields = '__all__'


class medication_update(UpdateView):
  model = Medications
  fields = ['name', 'startDate', 'endDate', 'amount']


class medication_delete(DeleteView):
  model = Medications
  success_url = '/medications/'


def bloodResult_index(request):   
    bloodSampleResults = BloodSample_Result.objects.all()
    return render(request, 'bloodResults/index.html', {'bloodSampleResults':bloodSampleResults})


def bloodResult_details(request, sample_id):
    bloodSampleResult = BloodSample_Result.objects.get (id=sample_id)
    return render(request, 'bloodResults/detail.html', {'bloodSampleResult':bloodSampleResult})

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}

<h1>About NIH</h1>

<p>The National Institutes of Health, commonly referred to as NIH (with each letter pronounced individually), is the primary agency of the United States government responsible for biomedical and public health research. It was founded in the late 1880s and is now part of the United States Department of Health and Human Services. <br><br>
    
    The majority of NIH facilities are located in Bethesda, Maryland, and other nearby suburbs of the Washington metropolitan area, with other primary facilities in the Research Triangle Park in North Carolina and smaller satellite facilities located around the United States. <br><br>
    
    The NIH conducts its own scientific research through the NIH Intramural Research Program (IRP) and provides major biomedical research funding to non-NIH research facilities through its Extramural Research Program.<br><br>

    As of 2013, the IRP had 1,200 principal investigators and more than 4,000 postdoctoral fellows in basic, translational, and clinical research, being the largest biomedical research institution in the world, while, as of 2003, the extramural arm provided 28% of biomedical research funding spent annually in the U.S., or about US$26.4 billion.<br><br>
    
    The NIH comprises 27 separate institutes and centers of different biomedical disciplines and is responsible for many scientific accomplishments, including the discovery of fluoride to prevent tooth decay, the use of lithium to manage bipolar disorder, and the creation of vaccines against hepatitis, Haemophilus influenzae (HIB), and human papillomavirus (HPV).[3]
    
    In 2019, the NIH was ranked number two in the world, behind Harvard University, for biomedical sciences in the Nature Index, which measured the largest contributors to papers published in a subset of leading journals from 2015 to 2018.</p>
{% endblock%}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Nanum+Gothic&display=swap"
      rel="stylesheet"
    />
    <title>National Institute of Health Lab</title>

    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
  </head>
  <body>
    <header>
      <img class="NIHLego" src="{% static 'images/nih-logo-color.png' %}" />
      <nav>
        <div>
          <ul>
            {% if user.is_authenticated %}
              <li class="navItem">
                <a class="navLink" href="{% url 'about' %}">About NIH</a>
              </li>
              <li class="navItem">
                <a class="navLink" href="{% url 'patient_create' %}">Add Patients</a>
              </li>
              <li class="navItem">
                <a class="navLink" href="{% url 'index' %}">View All Patients</a>
              </li>
              <li class="navItem">
                <a class="navLink" href="{% url 'medication_create' %}">Add Medications</a>
              </li>
              <li class="navItem">
                <a class="navLink" href="{% url 'medication_index' %}">View All Medications</a>
              </li>
              <li class="navItem">
                <a class="navLink" href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
              <li class="navItem"><a class="navLink" href="{% url 'signup' %}">Sign Up</a></li>
              <li class="navItem"><a class="navLink" href="{% url 'login' %}">Log In</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
      <div>
        National Institutes of Health, 9000 Rockville Pike, Bethesda, Maryland
        20892<br />
        U.S. Department of Health and Human Services
      </div>
    </footer>
  </body>
</html>

main_app/templates/bloodResults/detail.html
{% extends 'base.html' %} {% block content %}
<h1>Sampling list</h1>

<div>
  <div class="card-container">
    White Blood Cell (WBC): {{ sample.WBC }} <br />
    Red Blood Cell (RBC): {{ sample.RBC }} <br />
    Hematocrit (HCT): {{ sample.HCT }} <br />
    Mean Cell Volume (MCV): {{ sample.MCV }} <br />
    Mean Cell Hemogolobin (MCH): {{ sample.MCH }}<br /><br /><br />
  </div>
  <div>
    <a href="{% url 'sample_update' sample.id%}">Edit</a>
    <a href="{% url 'sample_delete' sample.id%}"></a>>Delete</a>
  </div>
</div>
{% endblock%}

main_app/templates/bloodResults/index.html
{% extends 'base.html' %} {% block content %}
<h1>Patients Blood Result Report</h1>
{% for sample in samples %}

<div>
  <div class="card-container">
    <a href="{% url 'detail' sample.id %}">Patient ID: Patient </a><br />
    White Blood Cell (WBC): {{ sample.WBC }} <br />
    Red Blood Cell (RBC): {{ sample.RBC }} <br />
    Hematocrit (HCT): {{ sample.HCT }} <br />
    Mean Cell Volume (MCV): {{ sample.MCV }} <br />
    Mean Cell Hemogolobin (MCH): {{ sample.MCH }}<br /><br /><br />
  </div>
</div>
{%endfor%} {% endblock%}

main_app/templates/index.html
{% extends 'base.html' %} {% block content %}
<h1>Index lab sampling</h1>
{% endblock %}

main_app/templates/main_app/medication_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Medication Details</h1>

{{ medication.name }}

{% endblock %}

main_app/templates/main_app/medications_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Medication Details</h1>

{{ medication.name }}

{% endblock %}

main_app/templates/main_app/medications_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Medications</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="submitButton">
  </form>
{% endblock %}

main_app/templates/main_app/medications_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Medication List</h1>

{% for m in medications_list %}
  <a href="{% url 'medication_detail' m.id  %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ m.name }}</span>
            <span class="card-title">{{ m.startDate }}</span>
            <span class="card-title">{{ m.endDate }}</span>
            <span class="card-title">{{ m.amount }}</span>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/patient_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Patient</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'details' patient.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/patient_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Patient</h1>
{% endif%}

<form action="" method="post">
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="submitButton" />
</form>
{% endblock%}

main_app/templates/patients/detail.html
{% extends 'base.html' %} {% block content %}
<h1>Patient Information</h1>

{% for photo in patient.photo_set.all %}
    <img
      class="card-panel teal-text center-align"
      src="{{ photo.url }}"
      alt="patient photo"
      style="max-width: 200px"
    />
    {% empty %}
    <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
    <form
      action="{% url 'add_photo' patient.id %}"
      enctype="multipart/form-data"
      method="POST"
      class="card-panel"
    >
      {% csrf_token %}
      <input type="file" name="photo-file" />
      <br /><br />
      <input type="submit" value="Upload Photo" />
    </form>
<div>
  <div class="list-container">
    <b>Patient Name:</b> {{ patient.name }} <br />
    <b>Age:</b> {{ patient.age }} <br />
    <b>sex:</b> {{ patient.sex }} <br />
    <b>Family Doctor:</b> {{ patient.family_doctor}} <br />
  </div>
  <div class="button_container">
    <div class="submitButton">
      <a href="{% url 'patient_update' patient.id%}">Edit</a>
    </div>
    <div class="submitButton">
      <a href="{% url 'patient_delete' patient.id%}">Delete</a>
    </div>
  </div>
</div>
<h1>Patient Blood Sampling</h1>
<div>
  <form action="{% url 'bloodSample_add' patient.id %}" method="post">
    {% csrf_token %} {{ patientBloodSample_form.as_p }}
    <input type="submit" class="submitButton" value="Add Blood Samples" />
  </form>
</div>

<div class="list-container">
 
    {% for sample in patient.bloodsamples_set.all %}   
        Sample Collection Date: {{sample.collectionDate}} <br>
        Ordering Physican: {{sample.orderingPhysician}} <br>   
    {% endfor %}
   
</div>

<hr />
<h1>Patient Medications</h1>
<div class="list-container">
  <div class="col s6">
   
    {% if patient.medications.count %} 
    {%for medication in patient.medications.all%}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          <span>Medications:</span> {{medication.name}} <br />
          <span>Date start:</span> {{medication.startDate}}<br />
          <span>Date finished:</span> {{medication.endDate}}<br />
          <span>Dose:</span> {{medication.amount}}<br />
        </span><br>
      </div>
    </div>
    {% endfor %} {% else %}
    <h5>No Medications</h5>
    {% endif %}
  </div>
  <!-- Available medications will come after this line -->

  <div class="col s6">
    <h2>Available Medications</h2>
    {% if medications.count %}
      {% for medication in medications.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              Medications: {{ medication.name }} <br>
              Start Date: {{ medication.startDate}} <br>
              End Date: {{ medication.endDate}} <br>
              Dose: {{ medication.amount}} <br>
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'patient_medication' patient.id medication.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="submitButton">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{cat.name}} All medications added</h5>
    {% endif %}
  </div>
</div>

{% endblock%}

main_app/templates/patients/index.html
{% extends 'base.html' %} {% block content %}
<h1>List of Patients</h1>
{% for patient in patients %}

<div>
  <div class="list-container">
    <b>Patient Name:</b>
    <a href="{% url 'details' patient.id %}">{{ patient.name }}</a> <br />
    <b>Age:</b> {{ patient.age }} <br />
    <b>SEX:</b> {{ patient.sex }} <br />
  </div>
</div>
{%endfor%} {% endblock%}

main_app/templates/patients_prescriptions/index.html
{% extends 'base.html' %} {% block content%}
<h1>List of Medicine</h1>

<% for medicine in medications%>
<div class="card">
  <div class="card-content">
    Medicine name: {{ medicine.name }} <br />
    Start date: {{ medicine.start_date }} <br />
    End date: {{ medicine.end_date }} <br />
    Amount: {{ medicine.amount }} <br />
  </div>
</div>
<% endfor%> {%endblock%}

main_app/templates/samples/detail.html
{% extends 'base.html' %} {% block content %}
<h1>Sampling list</h1>

<div>
  <div class="card-container">
    White Blood Cell (WBC): {{ sample.WBC }} <br />
    Red Blood Cell (RBC): {{ sample.RBC }} <br />
    Hematocrit (HCT): {{ sample.HCT }} <br />
    Mean Cell Volume (MCV): {{ sample.MCV }} <br />
    Mean Cell Hemogolobin (MCH): {{ sample.MCH }}<br /><br /><br />
  </div>
</div>
{% endblock%}

main_app/templates/samples/index.html
{% extends 'base.html' %} {% block content %}
<h1>Blood Ccount Sample Report</h1>
{% for sample in samples %}

<div>
  <div class="card-container">
    <a href="{% url 'detail' sample.id %}">Patient ID: Patient </a><br />
    White Blood Cell (WBC): {{ sample.WBC }} <br />
    Red Blood Cell (RBC): {{ sample.RBC }} <br />
    Hematocrit (HCT): {{ sample.HCT }} <br />
    Mean Cell Volume (MCV): {{ sample.MCV }} <br />
    Mean Cell Hemogolobin (MCH): {{ sample.MCH }}<br /><br /><br />
  </div>
</div>
{%endfor%} {% endblock%}